book_review_api:
    type: rest
    resource: "@BookReviewAPIBundle/Resources/config/routing.yml"
    prefix:   /api/v1

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

book_review_review:
    resource: "@BookReviewReviewBundle/Resources/config/routing.yml"
    prefix:   /

book_review_user:
    resource: "@BookReviewUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


